# You may want to blacklist certain tmux sessions from showing up in the results. 
# For example, you may want to exclude your scratch directory from the results.
blacklist = ["scratch"]

[default_session]
startup_command = "nvim -c ':SessionOrFiles'" # a custom command
preview_command = "eza --all --git --icons --color=always {}"

# COMMON

[[session]]
name = "Downloads ðŸ“¥(file manager)"
path = "~/Downloads"
startup_command = "y"

[[session]]
name = "Resume"
path = "~/Drive/Projects/Personal/my-resume/"

[[session]]
name = "Notes"
path = "~/Drive/Notes"

# CONFIGS

[[session]]
name = "dotfiles"
path = "~/.dotfiles"


[[session]]
name = "neovim config"
path = "~/.dotfiles/nvim/.config/nvim"

[[session]]
name = "tmux config"
path = "~/.dotfiles/tmux/"
startup_command = "nvim .tmux.conf"
preview_command = "bat --language=bash --style=snip --color=always ~/.dotfiles/tmux/.tmux.conf"

[[session]]
name = "sesh config[session manager]"
path = "~/.dotfiles/sesh/.config/sesh/"
startup_command = "nvim sesh.toml"

[[session]]
name = "bash config"
path = "~/.dotfiles/bash"
startup_command = "nvim -c ':SessionOrAllFiles'"

[[session]]
name = "yazi config"
path = "~/.dotfiles/yazi/.config/yazi"
startup_command = "nvim yazi.toml"

[[session]]
name = "custom scripts"
path = "~/.dotfiles/bin/.local/"

# WINDOWS

[[window]]
name = "git"
startup_script = "git pull && lazygit"
